### ISSUE TITLE
Can't change config on Hyprland

### ISSUE THREAD

**Issue by BeyondEternal** [SolDoesTech/HyprV3#10]
I have currently tried to change the HyprV3 settings in /home/beyond/HyprV3/HyprV/hypr/hyprland.conf, I save the changes but they are not reflected, I also looked to modify some things from the waybar that appear bugeadas as the microphone but it does not work.

![image](https://user-images.githubusercontent.com/36784347/235511422-759d0af2-f83d-4b67-a595-3a7743450c3c.png)

![image](https://user-images.githubusercontent.com/36784347/235511523-a7d4a7b1-6380-4800-bd6e-710735dd6ae8.png)

I also tried to add bind=$MainMod, F, fullscreen, and didn't work.

**Comment by S-Pika** [comment]
You are editing the config file in the wrong directory to change configs on hyperland you need to enter the hidden directory of .config then hypr and then the "hyperland.conf" file to edit. When you save the edits in that file they should apply immediately. example file path that hold the configs: /home/USERNAME/.config/hyper

**Comment by BeyondEternal** [comment]
You're rigth, I didn't notice hahahaha
