### ISSUE TITLE
Wofi start issue in v2 waybar

### ISSUE THREAD

**Issue by MotalaTech** [SolDoesTech/HyprV3#12]
Clicking the archicon in the upper left to launch wofi triggers strange behaviour.
Wherever I click on the waybar after that triggers wofistart again.

**Comment by SolDoesTech** [comment]
Hello, thanks for the feedback. I thought I had that issue all worked out.  How long ago did you download an install this? also, if you could please post your ~/.config/waybar/config.jsonc that would be helpful. Thank you.

**Comment by MotalaTech** [comment]
Perfect! Super! That fixed it :) ,and thanks for your work on this script.
