### ISSUE TITLE
Error when installing "Waybar-hyprland"

### ISSUE THREAD

**Issue by Batres3** [SolDoesTech/HyprV3#14]
I tried following the steps in the video but ran into an issue after running `./set-hypr`, the error seems to come from the command `yay -S waybar-hyprland` but I can’t seem to figure out why, apparently there is an error while compiling c++ files, I can’t copy paste but the last lines of the log are:
`ninja: build stopped: subcommand failed.` and `A failure occurred in build()`. Before that, in the log, there are a bunch of errors coming from `../src/modules/sway/ipc/client.cpp`

**Comment by Akinetopsia1** [comment]
having the same issue. Here is a screen capture of the last lines of the log,
![image](https://user-images.githubusercontent.com/106173717/236373215-33c1676f-ffb8-43f0-8bad-8f41f8c3235a.png)

**Comment by cahva** [comment]
I fixed this by changing the waybar-hyprland aur package to use the git version. So in this line https://github.com/SolDoesTech/HyprV3/blob/main/set-hypr#L182

Change `waybar-hyprland` -> `waybar-hyprland-git`

**Comment by Batres3** [comment]
Thanks! ended up reverting to my old distro because I couldn't be bothered to wait lol. But thanks anyways

**Comment by Akinetopsia1** [comment]
> I fixed this by changing the waybar-hyprland aur package to use the git version. So in this line https://github.com/SolDoesTech/HyprV3/blob/main/set-hypr#L182
> 
> Change `waybar-hyprland` -> `waybar-hyprland-git`

Yep that worked, thanks!

**Comment by JesseKoldewijn** [comment]
Sounds like the non-git pkgbuild for the aur package is kinda broken. This can happen and are kind of hard to catch externally😅
