### ISSUE TITLE
First install, stuck at login screen

### ISSUE THREAD

**Issue by DozersMC** [SolDoesTech/HyprV3#20]
As a disclaimer I am running Hyprland within vmware. I am getting stuck in the login screen. My installation has no issues itself but I'm still getting stuck at the login screen.

Running on a Mac, Intel chip

Thanks

**Comment by unsignedlongint69** [comment]
I'm fairly certain this is just a consequence of using a VM since the script did heavily suggest it will likely fail upon installation.

**Comment by DozersMC** [comment]
Yeah, thanks. I'm just live booting it at the moment but it's running extremely slowly on a very decent pc. Also I got it to run on the VM but could only see the top left corner. It wasnt working due to 3d accel being off. Thanks for your help
