### ISSUE TITLE
Small gift

### ISSUE THREAD

**Issue by kiryasolod** [SolDoesTech/HyprV3#4]
Hi, dear developer! I watched your last video on YouTube about your config and installer! I'm going to use it in a few days when I have some free time to reinstall my system. I want to send you one of my drawings I've created. Maybe you'd like to use it as a background image for one of your configs =)
Use my drawing for any purposes you want =)

To render the SVG file with the same quality I've rendered, you need to use Inkscape from flatpak or from the official site. Otherwise you will get gradient banding. Also enable "Use dithering" in Preferences -> Rendering

![Abstract02](https://user-images.githubusercontent.com/50103925/233966135-05c14ccb-36e4-477a-9b09-e7f535f61f6b.png)
![drawing](https://user-images.githubusercontent.com/50103925/233966268-7489e298-e15f-4b33-82a7-a4332bde7768.svg)

**Comment by SolDoesTech** [comment]
Very cool! thank you, I would try to put them to use on my next version :)

**Comment by kiryasolod** [comment]
Certainly! =) As I said, you can use them anyway you would like. And I would be happy to see them used =)
