### ISSUE TITLE
setbg doesnt seem to work on 30 series nvidia laptop

### ISSUE THREAD

**Issue by JesseKoldewijn** [SolDoesTech/HyprV3#5]
Here is my system lshw output (if useful):

<details>
<summary>Click me</summary>
<pre>
MyLaptop
    description: Notebook
    product: Vivobook_ASUSLaptop M6500RE_M6500RE
    vendor: ASUSTeK COMPUTER INC.
    version: 1.0
    width: 64 bits
    capabilities: smbios-3.4.0 dmi-3.4.0 smp vsyscall32
    configuration: boot=normal chassis=notebook family=Vivobook
  *-core
       description: Motherboard
       product: M6500RE
       vendor: ASUSTeK COMPUTER INC.
       physical id: 0
       version: 1.0
       slot: MIDDLE
     *-firmware
          description: BIOS
          vendor: American Megatrends International, LLC.
          physical id: 0
          version: M6500RE.311
          date: 11/22/2022
          size: 64KiB
          capacity: 32MiB
          capabilities: pci upgrade shadowing cdboot bootselect socketedrom edd acpi smartbattery biosbootspecification uefi
     *-cache:0
          description: L1 cache
          physical id: b
          slot: L1 - Cache
          size: 512KiB
          capacity: 512KiB
          clock: 1GHz (1.0ns)
          capabilities: pipeline-burst internal write-back unified
          configuration: level=1
     *-cache:1
          description: L2 cache
          physical id: c
          slot: L2 - Cache
          size: 4MiB
          capacity: 4MiB
          clock: 1GHz (1.0ns)
          capabilities: pipeline-burst internal write-back unified
          configuration: level=2
     *-cache:2
          description: L3 cache
          physical id: d
          slot: L3 - Cache
          size: 16MiB
          capacity: 16MiB
          clock: 1GHz (1.0ns)
          capabilities: pipeline-burst internal write-back unified
          configuration: level=3
     *-cpu
          description: CPU
          product: AMD Ryzen 9 6900HX with Radeon Graphics
          vendor: Advanced Micro Devices [AMD]
          physical id: e
          bus info: cpu@0
          version: AMD Ryzen 9 6900HX with Radeon Graphics
          serial: Unknown
          slot: FP7
          size: 2038MHz
          capacity: 4933MHz
          width: 64 bits
          clock: 100MHz
          capabilities: lm fpu fpu_exception wp vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp x86-64 constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd cppc arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl umip pku ospke vaes vpclmulqdq rdpid overflow_recov succor smca fsrm cpufreq
          configuration: cores=8 enabledcores=8 threads=16
     *-memory
          description: System Memory
          physical id: 10
          slot: System board or motherboard
          size: 16GiB
        *-bank:0
             description: Synchronous Unbuffered (Unregistered) 6400 MHz (0.2 ns)
             product: H9JCNNNCP3MLYR-N6E
             vendor: Unknown
             physical id: 0
             serial: 00000000
             slot: DIMM 0
             size: 4GiB
             width: 32 bits
             clock: 2105MHz (0.5ns)
        *-bank:1
             description: Synchronous Unbuffered (Unregistered) 6400 MHz (0.2 ns)
             product: H9JCNNNCP3MLYR-N6E
             vendor: Unknown
             physical id: 1
             serial: 00000000
             slot: DIMM 0
             size: 4GiB
             width: 32 bits
             clock: 2105MHz (0.5ns)
        *-bank:2
             description: Synchronous Unbuffered (Unregistered) 6400 MHz (0.2 ns)
             product: H9JCNNNCP3MLYR-N6E
             vendor: Unknown
             physical id: 2
             serial: 00000000
             slot: DIMM 0
             size: 4GiB
             width: 32 bits
             clock: 2105MHz (0.5ns)
        *-bank:3
             description: Synchronous Unbuffered (Unregistered) 6400 MHz (0.2 ns)
             product: H9JCNNNCP3MLYR-N6E
             vendor: Unknown
             physical id: 3
             serial: 00000000
             slot: DIMM 0
             size: 4GiB
             width: 32 bits
             clock: 2105MHz (0.5ns)
     *-pci:0
          description: Host bridge
          product: Family 17h-19h PCIe Root Complex
          vendor: Advanced Micro Devices, Inc. [AMD]
          physical id: 100
          bus info: pci@0000:00:00.0
          version: 01
          width: 32 bits
          clock: 33MHz
        *-generic UNCLAIMED
             description: IOMMU
             product: Family 17h-19h IOMMU
             vendor: Advanced Micro Devices, Inc. [AMD]
             physical id: 0.2
             bus info: pci@0000:00:00.2
             version: 00
             width: 32 bits
             clock: 33MHz
             capabilities: msi ht bus_master cap_list
             configuration: latency=0
        *-pci:0
             description: PCI bridge
             product: Advanced Micro Devices, Inc. [AMD]
             vendor: Advanced Micro Devices, Inc. [AMD]
             physical id: 1.1
             bus info: pci@0000:00:01.1
             version: 00
             width: 32 bits
             clock: 33MHz
             capabilities: pci pm pciexpress msi ht normal_decode bus_master cap_list
             configuration: driver=pcieport
             resources: irq:32 ioport:e000(size=4096) memory:dc000000-dd0fffff ioport:7e00000000(size=4328521728)
           *-display
                description: VGA compatible controller
                product: GA107M [GeForce RTX 3050 Ti Mobile]
                vendor: NVIDIA Corporation
                physical id: 0
                bus info: pci@0000:01:00.0
                logical name: /dev/fb0
                version: a1
                width: 64 bits
                clock: 33MHz
                capabilities: pm msi pciexpress vga_controller cap_list fb
                configuration: depth=32 latency=0 mode=2880x1620 visual=truecolor xres=2880 yres=1620
                resources: iomemory:7e0-7df iomemory:7f0-7ef memory:dc000000-dcffffff memory:7e00000000-7effffffff memory:7f00000000-7f01ffffff ioport:e000(size=128) memory:dd000000-dd07ffff
           *-multimedia
                description: Audio device
                product: NVIDIA Corporation
                vendor: NVIDIA Corporation
                physical id: 0.1
                bus info: pci@0000:01:00.1
                version: a1
                width: 32 bits
                clock: 33MHz
                capabilities: pm msi pciexpress bus_master cap_list
                configuration: driver=snd_hda_intel latency=0
                resources: irq:46 memory:dd080000-dd083fff
        *-pci:1
             description: PCI bridge
             product: Family 17h-19h PCIe GPP Bridge
             vendor: Advanced Micro Devices, Inc. [AMD]
             physical id: 2.2
             bus info: pci@0000:00:02.2
             version: 00
             width: 32 bits
             clock: 33MHz
             capabilities: pci pm pciexpress msi ht normal_decode bus_master cap_list
             configuration: driver=pcieport
             resources: irq:33 memory:dda00000-ddbfffff
           *-network
                description: Wireless interface
                product: MT7922 802.11ax PCI Express Wireless Network Adapter
                vendor: MEDIATEK Corp.
                physical id: 0
                bus info: pci@0000:02:00.0
                logical name: wlp2s0
                version: 00
                serial: 30:03:c8:38:34:db
                width: 64 bits
                clock: 33MHz
                capabilities: pciexpress msi pm bus_master cap_list ethernet physical wireless
                configuration: broadcast=yes driver=mt7921e driverversion=6.2.12-zen1-1-zen firmware=____000000-20221227123243 ip=10.10.10.32 latency=0 link=yes multicast=yes wireless=IEEE 802.11
                resources: irq:90 memory:dda00000-ddafffff memory:ddb00000-ddb07fff
        *-pci:2
             description: PCI bridge
             product: Family 17h-19h PCIe GPP Bridge
             vendor: Advanced Micro Devices, Inc. [AMD]
             physical id: 2.4
             bus info: pci@0000:00:02.4
             version: 00
             width: 32 bits
             clock: 33MHz
             capabilities: pci pm pciexpress msi ht normal_decode bus_master cap_list
             configuration: driver=pcieport
             resources: irq:34 memory:ddc00000-ddcfffff
           *-nvme
                description: NVMe device
                product: WDS200T3X0C-00SJG0
                vendor: Sandisk Corp
                physical id: 0
                bus info: pci@0000:03:00.0
                logical name: /dev/nvme0
                version: 102430WD
                serial: 192321447401
                width: 64 bits
                clock: 33MHz
                capabilities: nvme pm msi msix pciexpress nvm_express bus_master cap_list
                configuration: driver=nvme latency=0 nqn=nqn.2018-01.com.wdc:nguid:192321447401-0001-001B444A445498B2 state=live
                resources: irq:47 memory:ddc00000-ddc03fff memory:ddc04000-ddc040ff
              *-namespace:0
                   description: NVMe disk
                   physical id: 0
                   logical name: hwmon3
              *-namespace:1
                   description: NVMe disk
                   physical id: 2
                   logical name: /dev/ng0n1
              *-namespace:2
                   description: NVMe disk
                   physical id: 1
                   bus info: nvme@0:1
                   logical name: /dev/nvme0n1
                   size: 1863GiB (2TB)
                   capabilities: gpt-1.00 partitioned partitioned:gpt
                   configuration: guid=36889d07-63b3-4489-bdbf-6a019432e626 logicalsectorsize=512 sectorsize=512 wwid=eui.1923214474010001001b444a445498b2
                 *-volume:0 UNCLAIMED
                      description: Windows FAT volume
                      vendor: mkfs.fat
                      physical id: 1
                      bus info: nvme@0:1,1
                      version: FAT32
                      serial: 00fe-8033
                      size: 509MiB
                      capacity: 510MiB
                      capabilities: boot fat initialized
                      configuration: FATs=2 filesystem=fat name=primary
                 *-volume:1
                      description: EFI partition
                      physical id: 2
                      bus info: nvme@0:1,2
                      logical name: /dev/nvme0n1p2
                      logical name: /
                      logical name: /.snapshots
                      logical name: /home
                      logical name: /var/cache/pacman/pkg
                      logical name: /var/log
                      serial: eca2b513-9a32-4a2c-9d83-0abe8b6b8172
                      capacity: 1862GiB
                      configuration: mount.fstype=btrfs mount.options=rw,relatime,ssd,discard=async,space_cache=v2,subvolid=258,subvol=/@log name=primary state=mounted
        *-pci:3
             description: PCI bridge
             product: Family 19h USB4/Thunderbolt PCIe tunnel
             vendor: Advanced Micro Devices, Inc. [AMD]
             physical id: 3.1
             bus info: pci@0000:00:03.1
             version: 00
             width: 32 bits
             clock: 33MHz
             capabilities: pci pm pciexpress msi ht normal_decode bus_master cap_list
             configuration: driver=pcieport
             resources: irq:35 ioport:b000(size=8192) memory:c4000000-dbffffff ioport:7f10000000(size=671088640)
        *-pci:4
             description: PCI bridge
             product: Family 17h-19h Internal PCIe GPP Bridge
             vendor: Advanced Micro Devices, Inc. [AMD]
             physical id: 8.1
             bus info: pci@0000:00:08.1
             version: 10
             width: 32 bits
             clock: 33MHz
             capabilities: pci pm pciexpress msi normal_decode bus_master cap_list
             configuration: driver=pcieport
             resources: irq:36 ioport:d000(size=4096) memory:dd600000-dd9fffff ioport:7f40000000(size=270532608)
           *-display
                description: VGA compatible controller
                product: Rembrandt [Radeon 680M]
                vendor: Advanced Micro Devices, Inc. [AMD/ATI]
                physical id: 0
                bus info: pci@0000:34:00.0
                version: 01
                width: 64 bits
                clock: 33MHz
                capabilities: pm pciexpress msi msix vga_controller bus_master cap_list
                configuration: driver=amdgpu latency=0
                resources: iomemory:7f0-7ef iomemory:7f0-7ef irq:40 memory:7f40000000-7f4fffffff memory:7f50000000-7f501fffff ioport:d000(size=256) memory:dd900000-dd97ffff
           *-multimedia:0
                description: Audio device
                product: Rembrandt Radeon High Definition Audio Controller
                vendor: Advanced Micro Devices, Inc. [AMD/ATI]
                physical id: 0.1
                bus info: pci@0000:34:00.1
                version: 00
                width: 32 bits
                clock: 33MHz
                capabilities: pm pciexpress msi bus_master cap_list
                configuration: driver=snd_hda_intel latency=0
                resources: irq:87 memory:dd9c8000-dd9cbfff
           *-generic
                description: Encryption controller
                product: VanGogh PSP/CCP
                vendor: Advanced Micro Devices, Inc. [AMD]
                physical id: 0.2
                bus info: pci@0000:34:00.2
                version: 00
                width: 32 bits
                clock: 33MHz
                capabilities: pm pciexpress msi msix bus_master cap_list
                configuration: driver=ccp latency=0
                resources: irq:83 memory:dd800000-dd8fffff memory:dd9cc000-dd9cdfff
           *-usb:0
                description: USB controller
                product: Rembrandt USB4 XHCI controller #3
                vendor: Advanced Micro Devices, Inc. [AMD]
                physical id: 0.3
                bus info: pci@0000:34:00.3
                version: 00
                width: 64 bits
                clock: 33MHz
                capabilities: pm pciexpress msi msix xhci bus_master cap_list
                configuration: driver=xhci_hcd latency=0
                resources: irq:39 memory:dd700000-dd7fffff
              *-usbhost:0
                   product: xHCI Host Controller
                   vendor: Linux 6.2.12-zen1-1-zen xhci-hcd
                   physical id: 0
                   bus info: usb@1
                   logical name: usb1
                   version: 6.02
                   capabilities: usb-2.00
                   configuration: driver=hub slots=4 speed=480Mbit/s
              *-usbhost:1
                   product: xHCI Host Controller
                   vendor: Linux 6.2.12-zen1-1-zen xhci-hcd
                   physical id: 1
                   bus info: usb@2
                   logical name: usb2
                   version: 6.02
                   capabilities: usb-3.10
                   configuration: driver=hub slots=2 speed=10000Mbit/s
           *-usb:1
                description: USB controller
                product: Rembrandt USB4 XHCI controller #4
                vendor: Advanced Micro Devices, Inc. [AMD]
                physical id: 0.4
                bus info: pci@0000:34:00.4
                version: 00
                width: 64 bits
                clock: 33MHz
                capabilities: pm pciexpress msi msix xhci bus_master cap_list
                configuration: driver=xhci_hcd latency=0
                resources: irq:41 memory:dd600000-dd6fffff
              *-usbhost:0
                   product: xHCI Host Controller
                   vendor: Linux 6.2.12-zen1-1-zen xhci-hcd
                   physical id: 0
                   bus info: usb@3
                   logical name: usb3
                   version: 6.02
                   capabilities: usb-2.00
                   configuration: driver=hub slots=3 speed=480Mbit/s
                 *-usb:0 UNCLAIMED
                      description: Generic USB device
                      product: FocalTech Fingerprint Device
                      vendor: Realtek USB2.0 Finger Print Bridge
                      physical id: 1
                      bus info: usb@3:1
                      version: 1.11
                      capabilities: usb-2.00
                      configuration: maxpower=100mA speed=480Mbit/s
                 *-usb:1
                      description: Bluetooth wireless interface
                      product: Wireless_Device
                      vendor: MediaTek Inc.
                      physical id: 2
                      bus info: usb@3:2
                      version: 1.00
                      serial: 000000000
                      capabilities: usb-2.10 bluetooth
                      configuration: driver=btusb maxpower=100mA speed=480Mbit/s
                 *-usb:2
                      description: Video
                      product: USB2.0 FHD UVC WebCam
                      vendor: Sonix Technology Co., Ltd.
                      physical id: 3
                      bus info: usb@3:3
                      version: 0.03
                      capabilities: usb-2.01
                      configuration: driver=uvcvideo maxpower=500mA speed=480Mbit/s
              *-usbhost:1
                   product: xHCI Host Controller
                   vendor: Linux 6.2.12-zen1-1-zen xhci-hcd
                   physical id: 1
                   bus info: usb@4
                   logical name: usb4
                   version: 6.02
                   capabilities: usb-3.10
                   configuration: driver=hub slots=2 speed=10000Mbit/s
           *-multimedia:1
                description: Multimedia controller
                product: ACP/ACP3X/ACP6x Audio Coprocessor
                vendor: Advanced Micro Devices, Inc. [AMD]
                physical id: 0.5
                bus info: pci@0000:34:00.5
                version: 60
                width: 32 bits
                clock: 33MHz
                capabilities: pm pciexpress msi bus_master cap_list
                configuration: driver=snd_pci_acp6x latency=0
                resources: irq:86 memory:dd980000-dd9bffff
           *-multimedia:2
                description: Audio device
                product: Family 17h/19h HD Audio Controller
                vendor: Advanced Micro Devices, Inc. [AMD]
                physical id: 0.6
                bus info: pci@0000:34:00.6
                version: 00
                width: 32 bits
                clock: 33MHz
                capabilities: pm pciexpress msi bus_master cap_list
                configuration: driver=snd_hda_intel latency=0
                resources: irq:88 memory:dd9c0000-dd9c7fff
        *-pci:5
             description: PCI bridge
             product: Family 17h-19h Internal PCIe GPP Bridge
             vendor: Advanced Micro Devices, Inc. [AMD]
             physical id: 8.3
             bus info: pci@0000:00:08.3
             version: 10
             width: 32 bits
             clock: 33MHz
             capabilities: pci pm pciexpress msi normal_decode bus_master cap_list
             configuration: driver=pcieport
             resources: irq:37 memory:dd200000-dd5fffff
           *-usb:0
                description: USB controller
                product: Rembrandt USB4 XHCI controller #8
                vendor: Advanced Micro Devices, Inc. [AMD]
                physical id: 0
                bus info: pci@0000:35:00.0
                version: 00
                width: 64 bits
                clock: 33MHz
                capabilities: pm pciexpress msi msix xhci bus_master cap_list
                configuration: driver=xhci_hcd latency=0
                resources: irq:43 memory:dd400000-dd4fffff
              *-usbhost:0
                   product: xHCI Host Controller
                   vendor: Linux 6.2.12-zen1-1-zen xhci-hcd
                   physical id: 0
                   bus info: usb@5
                   logical name: usb5
                   version: 6.02
                   capabilities: usb-2.00
                   configuration: driver=hub slots=1 speed=480Mbit/s
              *-usbhost:1
                   product: xHCI Host Controller
                   vendor: Linux 6.2.12-zen1-1-zen xhci-hcd
                   physical id: 1
                   bus info: usb@6
                   logical name: usb6
                   version: 6.02
                   capabilities: usb-3.00
                   configuration: speed=5000Mbit/s
           *-usb:1
                description: USB controller
                product: Rembrandt USB4 XHCI controller #5
                vendor: Advanced Micro Devices, Inc. [AMD]
                physical id: 0.3
                bus info: pci@0000:35:00.3
                version: 00
                width: 64 bits
                clock: 33MHz
                capabilities: pm pciexpress msi msix xhci bus_master cap_list
                configuration: driver=xhci_hcd latency=0
                resources: irq:45 memory:dd300000-dd3fffff
              *-usbhost:0
                   product: xHCI Host Controller
                   vendor: Linux 6.2.12-zen1-1-zen xhci-hcd
                   physical id: 0
                   bus info: usb@7
                   logical name: usb7
                   version: 6.02
                   capabilities: usb-2.00
                   configuration: driver=hub slots=1 speed=480Mbit/s
              *-usbhost:1
                   product: xHCI Host Controller
                   vendor: Linux 6.2.12-zen1-1-zen xhci-hcd
                   physical id: 1
                   bus info: usb@8
                   logical name: usb8
                   version: 6.02
                   capabilities: usb-3.10
                   configuration: driver=hub slots=1 speed=10000Mbit/s
           *-usb:2
                description: USB controller
                product: Rembrandt USB4 XHCI controller #6
                vendor: Advanced Micro Devices, Inc. [AMD]
                physical id: 0.4
                bus info: pci@0000:35:00.4
                version: 00
                width: 64 bits
                clock: 33MHz
                capabilities: pm pciexpress msi msix xhci bus_master cap_list
                configuration: driver=xhci_hcd latency=0
                resources: irq:49 memory:dd200000-dd2fffff
              *-usbhost:0
                   product: xHCI Host Controller
                   vendor: Linux 6.2.12-zen1-1-zen xhci-hcd
                   physical id: 0
                   bus info: usb@9
                   logical name: usb9
                   version: 6.02
                   capabilities: usb-2.00
                   configuration: driver=hub slots=1 speed=480Mbit/s
              *-usbhost:1
                   product: xHCI Host Controller
                   vendor: Linux 6.2.12-zen1-1-zen xhci-hcd
                   physical id: 1
                   bus info: usb@10
                   logical name: usb10
                   version: 6.02
                   capabilities: usb-3.10
                   configuration: driver=hub slots=1 speed=10000Mbit/s
           *-usb:3
                description: USB controller
                product: Rembrandt USB4/Thunderbolt NHI controller #1
                vendor: Advanced Micro Devices, Inc. [AMD]
                physical id: 0.5
                bus info: pci@0000:35:00.5
                version: 00
                width: 64 bits
                clock: 33MHz
                capabilities: pm pciexpress msi msix usb4_host_interface bus_master cap_list
                configuration: driver=thunderbolt latency=0
                resources: irq:42 memory:dd500000-dd57ffff
        *-serial
             description: SMBus
             product: FCH SMBus Controller
             vendor: Advanced Micro Devices, Inc. [AMD]
             physical id: 14
             bus info: pci@0000:00:14.0
             version: 71
             width: 32 bits
             clock: 66MHz
             configuration: driver=piix4_smbus latency=0
             resources: irq:0
        *-isa
             description: ISA bridge
             product: FCH LPC Bridge
             vendor: Advanced Micro Devices, Inc. [AMD]
             physical id: 14.3
             bus info: pci@0000:00:14.3
             version: 51
             width: 32 bits
             clock: 66MHz
             capabilities: isa bus_master
             configuration: latency=0
     *-pci:1
          description: Host bridge
          product: Family 17h-19h PCIe Dummy Host Bridge
          vendor: Advanced Micro Devices, Inc. [AMD]
          physical id: 101
          bus info: pci@0000:00:01.0
          version: 01
          width: 32 bits
          clock: 33MHz
     *-pci:2
          description: Host bridge
          product: Family 17h-19h PCIe Dummy Host Bridge
          vendor: Advanced Micro Devices, Inc. [AMD]
          physical id: 102
          bus info: pci@0000:00:02.0
          version: 01
          width: 32 bits
          clock: 33MHz
     *-pci:3
          description: Host bridge
          product: Family 17h-19h PCIe Dummy Host Bridge
          vendor: Advanced Micro Devices, Inc. [AMD]
          physical id: 103
          bus info: pci@0000:00:03.0
          version: 01
          width: 32 bits
          clock: 33MHz
     *-pci:4
          description: Host bridge
          product: Family 17h-19h PCIe Dummy Host Bridge
          vendor: Advanced Micro Devices, Inc. [AMD]
          physical id: 104
          bus info: pci@0000:00:04.0
          version: 01
          width: 32 bits
          clock: 33MHz
     *-pci:5
          description: Host bridge
          product: Family 17h-19h PCIe Dummy Host Bridge
          vendor: Advanced Micro Devices, Inc. [AMD]
          physical id: 105
          bus info: pci@0000:00:08.0
          version: 01
          width: 32 bits
          clock: 33MHz
     *-pci:6
          description: Host bridge
          product: Rembrandt Data Fabric: Device 18h; Function 0
          vendor: Advanced Micro Devices, Inc. [AMD]
          physical id: 106
          bus info: pci@0000:00:18.0
          version: 00
          width: 32 bits
          clock: 33MHz
     *-pci:7
          description: Host bridge
          product: Rembrandt Data Fabric: Device 18h; Function 1
          vendor: Advanced Micro Devices, Inc. [AMD]
          physical id: 107
          bus info: pci@0000:00:18.1
          version: 00
          width: 32 bits
          clock: 33MHz
     *-pci:8
          description: Host bridge
          product: Rembrandt Data Fabric: Device 18h; Function 2
          vendor: Advanced Micro Devices, Inc. [AMD]
          physical id: 108
          bus info: pci@0000:00:18.2
          version: 00
          width: 32 bits
          clock: 33MHz
     *-pci:9
          description: Host bridge
          product: Rembrandt Data Fabric: Device 18h; Function 3
          vendor: Advanced Micro Devices, Inc. [AMD]
          physical id: 109
          bus info: pci@0000:00:18.3
          version: 00
          width: 32 bits
          clock: 33MHz
          configuration: driver=k10temp
          resources: irq:0
     *-pci:10
          description: Host bridge
          product: Rembrandt Data Fabric: Device 18h; Function 4
          vendor: Advanced Micro Devices, Inc. [AMD]
          physical id: 10a
          bus info: pci@0000:00:18.4
          version: 00
          width: 32 bits
          clock: 33MHz
     *-pci:11
          description: Host bridge
          product: Rembrandt Data Fabric: Device 18h; Function 5
          vendor: Advanced Micro Devices, Inc. [AMD]
          physical id: 10b
          bus info: pci@0000:00:18.5
          version: 00
          width: 32 bits
          clock: 33MHz
     *-pci:12
          description: Host bridge
          product: Rembrandt Data Fabric: Device 18h; Function 6
          vendor: Advanced Micro Devices, Inc. [AMD]
          physical id: 10c
          bus info: pci@0000:00:18.6
          version: 00
          width: 32 bits
          clock: 33MHz
     *-pci:13
          description: Host bridge
          product: Rembrandt Data Fabric: Device 18h; Function 7
          vendor: Advanced Micro Devices, Inc. [AMD]
          physical id: 10d
          bus info: pci@0000:00:18.7
          version: 00
          width: 32 bits
          clock: 33MHz
     *-pnp00:00
          product: System Board
          physical id: 1
          capabilities: pnp
          configuration: driver=system
     *-pnp00:01
          product: AT Real-Time Clock
          physical id: 2
          capabilities: pnp
          configuration: driver=rtc_cmos
     *-pnp00:02
          product: PnP device ATK3001
          vendor: Allied Telesyn Int'l
          physical id: 3
          capabilities: pnp
          configuration: driver=i8042 kbd
     *-pnp00:03
          product: Motherboard registers
          physical id: 4
          capabilities: pnp
          configuration: driver=system
</pre>
</details

**Comment by JesseKoldewijn** [comment]
Moved my setup on my laptop from the v2 to v3 setup (after I removed the v2 files). I also checked if I could call the setbg myself but this just gives me the tooltip content I believe.

**Comment by FatngatirBilek** [comment]
@JesseKoldewijn are you change your resolution?

**Comment by FatngatirBilek** [comment]
i have same problem after trying to change my resolution

**Comment by JesseKoldewijn** [comment]
> 

Changed the res afterwards just to check if that config might have something to do with it but not initially.

**Comment by JesseKoldewijn** [comment]
> hyprland desktop backround brakes if you change the scaleing i still use swaybg for that reason wich just works fine

Funny enough I didn't even touch the scaling. Only changed the resolution. 😅

**Comment by SolDoesTech** [comment]
Hello, swww does have issue with both scaling and resolution change. It has to do with the way it loads the image into memory. As far as the socket error, I think it has to do to an error in the script, I was loading swww at the wrong time. The git repo had been updated so the 2 files that need to change are hyprland.conf and hyprv_util, the commit info can be found here https://github.com/SolDoesTech/HyprV3/commit/10a1ad35488d8684339e1742c47f78d5a9fb8dca

**Comment by JesseKoldewijn** [comment]
> Hello, swww does have issue with both scaling and resolution change. It has to do with the way it loads the image into memory. As far as the socket error, I think it has to do to an error in the script, I was loading swww at the wrong time. The git repo had been updated so the 2 files that need to change are hyprland.conf and hyprv_util, the commit info can be found here https://github.com/SolDoesTech/HyprV3/commit/10a1ad35488d8684339e1742c47f78d5a9fb8dca

Thanks man, I saw the swww change but overlooked the change on the hyprv_util file (only updated the conf with no dice)😅

**Comment by JesseKoldewijn** [comment]
OS socket issue was related to the swww cache. Just remove the ~/.cache/swww directory, run swww kill and then swww init and all works fine again.
