### ISSUE TITLE
waybar-hyperland

### ISSUE THREAD

**Issue by vikipretium** [SolDoesTech/HyprV3#6]
![image](https://user-images.githubusercontent.com/20333314/234515108-6e3e2f8b-50b8-4ef9-994b-b0d61f0f3929.png)
![image](https://user-images.githubusercontent.com/20333314/234515806-1e259487-93f2-40b2-b793-8848035e29e1.png)

getting this problem after running hyperV3 set-hypr

**Comment by JesseKoldewijn** [comment]
prob means ur arch mirrorlist is out of date ;)
you can update your mirrorlist with reflector for instance: https://wiki.archlinux.org/title/reflector

**Comment by vikipretium** [comment]
> prob means ur arch mirrorlist is out of date ;) you can update your mirrorlist with reflector for instance: https://wiki.archlinux.org/title/reflector

Thanks man 👍🏼 
I hope this will be helpful for further reference, if someone else face this same issue.
https://youtu.be/OevOyFUOXpE

**Comment by vikipretium** [comment]
![image](https://user-images.githubusercontent.com/20333314/234772276-f8f41582-0f51-40f4-a0d3-ccb7780522fd.png)
Thanks man @JesseKoldewijn 
It works ! 👍🏼
